### ISSUE TITLE
[BUG]: Redirection Issue : Clicking on CampX Logo Reloads Same Page

### ISSUE THREAD

**Issue by faiz66388** [VigneshDevHub/CampX#187] opened 2024-10-15 07:06 UTC
Description:
When clicking on the CampX logo in the navigation bar, it reloads the current page instead of redirecting to the home page as expected.

Steps to Reproduce:
Go to any page within the application, such as the login page.
Click on the "CampX" logo in the top-left corner of the navigation bar.
Expected Behavior:
Clicking on the "CampX" logo should redirect the user to the home page.

Actual Behavior:
Clicking on the "CampX" logo reloads the current page instead of redirecting to the home page.

Screenshots/Logs:
![image](https://github.com/user-attachments/assets/0f04c894-fd6c-42ea-933b-5ee71a24c3c9)

**Comment by Vignesh025** [comment] 2024-10-15 17:24
Hey @faiz66388 , you can proceed!

**Comment by faiz66388** [comment] 2024-10-16 07:03
Could you please assign labels gssoc-ext, hacktoberfest-accepted and level?

**Comment by raj-adi00** [comment] 2024-10-25 19:57
Is this issue open?? i can work on this

**Comment by Vignesh025** [comment] 2024-10-26 07:30
Hey @raj-adi00 , You can proceed!

**Comment by raj-adi00** [comment] 2024-10-26 09:39
@Vignesh025 Please confirm whether this issue still exist. I checked it is implemented on campgrounds page but not on home page

**Comment by raj-adi00** [comment] 2024-10-26 09:39
Do you want me to implement it on home page or you can close the issue

**Comment by Vignesh025** [comment] 2024-10-26 11:40
@raj-adi00 , yes the issue is solved.

**Closed by Vignesh025** 2024-10-26 11:40 UTC
Labels: gssoc-ext, hacktoberfest-accepted, level1
